POST https://api.stylizedace.dk/api/v1/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "role": "admin"
}

###


GET https://api.stylizedace.dk/api/v1/person


### Login as admin
POST https://api.stylizedace.dk/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


### extra post

POST https://api.stylizedace.dk/api/v1/person
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjcGhidXNpbmVzcy5kayIsInN1YiI6ImFkbWluIiwiZXhwIjoxNzAxMjY0MTYxLCJyb2xlcyI6ImFkbWluIiwidXNlcm5hbWUiOiJhZG1pbiJ9._OnbaKS7NR5leyArNANRv2Gzj-QOKVFbYZpDBpro_0s

{
  "firstName": "Dennis",
  "lastName": "Hansen",
  "age": "55",
  "email": "karl@mail.com"
}